site_name: Dokumentace Roští.cz
site_description: Dokumentace k hostingovým službám Roští.cz.
nav:
    - Domů: index.md
    - "Quickstart průvodce":
      - "1. První aplikace": "cs/quickstart/first_app.md"
      - "2. Jednoduchý deployment": cs/quickstart/first_deployment.md
      - "3. Databáze": cs/quickstart/databases.md
      - "4. Nastavení domény": cs/quickstart/domains.md
      - "4. Použití nástroje rostictl": cs/quickstart/rostictl.md
    - Technologie:
        - Python: cs/apps/python.md
        - PHP: cs/apps/php.md
        - Node.js: cs/apps/nodejs.md
        - Deno: cs/apps/deno.md
        - Golang: cs/apps/golang.md
    - "Další informace":
        - "Platby za služby": cs/billing.md
        - "Runtime prostředí": cs/runtime.md
        - "Nástroj rosti.sh": cs/rosti_sh.md
        - "Adresářová struktura /srv": cs/srv.md
        - "Správa služeb běžících na pozadí": cs/supervisor.md
        - "Připojení k SSH a databázím z venku": cs/ssh.md
        - "Instalace extra balíčků do systému": cs/extra-packages.md
        - "Cron": cs/cron.md
        - "Memcached a Redis": cs/memcached_redis.md
        - "MongoDB": cs/mongo.md
        - "SMTP server pro odchozí emaily": cs/smtp.md
        - "API": cs/api.md
        - "FAQ": cs/faq.md
    - "Stará dokumentace": old/index.md
theme: readthedocs
markdown_extensions:
  - admonition
  - pymdownx.details
